### ISSUE TITLE
Build tests for getCaste

### ISSUE THREAD

**Issue by gregorgorjanc** [HighlanderLab/SIMplyBee#100]
There is lots of edge cases in there and the package code relies on it big time, so we want to make sure this works as intended

**Comment by gregorgorjanc** [comment]
@janaobsteter do we have any tests for getCaste()?

**Comment by janaobsteter** [comment]
We actually don't. I'll write it now and add it to the PR #470

**Comment by LStrachan** [comment]
Built and working correctly now.
