### ISSUE TITLE
Add more summaries to the Colonies show method

### ISSUE THREAD

**Issue by gregorgorjanc** [HighlanderLab/SIMplyBee#108]
When we print out Colonies object, we say only how many colonies we have inside.

I suggest we add more summaries to ease inspection. For example, print how many have the queen, virgin queens, ... Perhaps we mirror the Colony show method, but here we report number of colonies with or without something.

I think this will ease hunting down colonies in an "odd" state. Both due to programming or scripting failures.

**Comment by gregorgorjanc** [comment]
Is there anything else that we want to add to the summary/show method of MultiColony or Colony object? Or shall we just close this issue for now?

**Comment by janaobsteter** [comment]
I think we are good for now!
