### ISSUE TITLE
Consolidate parameter default in functions

### ISSUE THREAD

**Issue by janaobsteter** [HighlanderLab/SIMplyBee#170]
In some functions we specify the defaults for all the parameters, such as in the createColony()
`createColonies <- function(pop = NULL, nCol = NULL, mated = TRUE,
                                            nAvgFathers = 15, nDronesPerQueen = 100,
                                            yearOfBirth = NULL, simParamBee = NULL)`

but in some of them we specify nothing
`crossColonies <- function(colonies, DCA, nAvgFathers, simParamBee = NULL)`

**Comment by LStrachan** [comment]
See issue #462 to resolve this
