### ISSUE TITLE
Plan SIMplyBee workshops

### ISSUE THREAD

**Issue by janaobsteter** [HighlanderLab/SIMplyBee#380]
Possible funding support:

- Dennis Trust: https://www.cbdennistrust.org.uk/
- Apimondia / EuroBee / EAAP

Possible venues:
- Apimondia (Chile 2023)
- EuroBee (2024?)
- EAAP (2023)
- COLOSS honeybee breeding workshops

**Comment by gregorgorjanc** [comment]
Will close this - we have other things to focus on.
