### ISSUE TITLE
Check whether the simulator could also work for other Apis species?

### ISSUE THREAD

**Issue by janaobsteter** [HighlanderLab/SIMplyBee#382]
Could we use our simulator also for Apis cerana, Apis florea etc. - do they have the same biological principles? This would increase the value of our simulator AND also the paper (we could write the intro about bees in general, not specifically on honeybees)

**Comment by gregorgorjanc** [comment]
I think this is sorted or is there any clear action we can/should/must do?

**Comment by janaobsteter** [comment]
I think I asked @JerBub to check this in the paper - and do we mention it in the paper now.
