### ISSUE TITLE
Use simplybee.info

### ISSUE THREAD

**Issue by gregorgorjanc** [HighlanderLab/SIMplyBee#421]
OK, we have the simplybee.info registered and purchased for 5 years. These are options I am given

![Screenshot 2022-11-02 at 15 28 36](https://user-images.githubusercontent.com/725834/199531637-d971b18a-4528-4bdb-8d31-51e2d0524813.png)

Will we point the domain to a GitHub version of pkgdown documentation? How do we do this? @LStrachan please talk to Thiago.

**Comment by LStrachan** [comment]
@gregorgorjanc Pkgdown is having trouble with the new vignettes but I think Jana has fixed it in her new PR if you can merge it :)
