### ISSUE TITLE
Move logo to another folder

### ISSUE THREAD

**Issue by gregorgorjanc** [HighlanderLab/SIMplyBee#446]
Currently the logo sits in `SIMplyBee/man/figures` folder, which is an odd place. Best if we put it somewhere else, say `SIMplyBee/logo` or `SIMplyBee/vignettes/figures` (along with flow charts of colony events).

@LStrachan I will assign you to this since you are in charge of flow charts or colony events.

**Comment by LStrachan** [comment]
Moved to logo folder

**Comment by gregorgorjanc** [comment]
@LStrachan @janaobsteter we have duplicated images in the package in the repository - see below - its this on purpose or by accident - we want one file version so we only ever worry about updating one version - or are the figures in docs copied there automatically by pkgdown?
<img width="492" alt="Screenshot 2022-12-08 at 17 28 21" src="https://user-images.githubusercontent.com/725834/206522787-90c94179-dc1d-4b12-85a8-9b1b7fa79cf6.png">
<img width="488" alt="Screenshot 2022-12-08 at 17 27 51" src="https://user-images.githubusercontent.com/725834/206522798-f47c2ba1-bb4a-47e3-8f0a-9e2f873a7cd3.png">

**Comment by janaobsteter** [comment]
@gg, we are not putting `docs/` into the package - `docs/` is created completely by pkgdown.

**Comment by gregorgorjanc** [comment]
So, pkgdown copies the man/figures folder? But, are these figures ever shown in man files or just in vignettes, in which case they should probably be in the vignettes folder?

**Comment by janaobsteter** [comment]
I googled where to put figures and found this recommendation. But I'll google again to see if there is a different recommendation for the vignettes figures.

**Comment by LStrachan** [comment]
All moved from man/figures to vignettes/

**Comment by gregorgorjanc** [comment]
OK, closing this issue then. Yay one more down!
