### ISSUE TITLE
Link SIMplyBee logo to README

### ISSUE THREAD

**Issue by gregorgorjanc** [HighlanderLab/SIMplyBee#451]
SIMplyBee logo is soo nice! We really must show it everywhere we can. @LStrachan can you figure out how to include it in the GitHub README.md file?

**Comment by gregorgorjanc** [comment]
@LStrachan please look into this - we made the repo public and now is the time for your logo to shine!

**Comment by LStrachan** [comment]
Added to the ReadMe. If we change the location of the logo, we need to change the image pathway
