### ISSUE TITLE
Add NEWS.md file that will track changes/news across package versions

### ISSUE THREAD

**Issue by gregorgorjanc** [HighlanderLab/SIMplyBee#473]
We should start this file now that we will make the first release and then continually update it as we add new features, fix bugs, etc. Ideally we would always add issue or commit number for each such step in this file.

**Comment by janaobsteter** [comment]
@gregorgorjanc , we already have NEWS.rd, but it currently includes only headings. Do we want to add something in?

**Comment by gregorgorjanc** [comment]
Maybe date of first CRAN release - best to update this file on the fly (with every PR) such that when we merge into main we know what the new version brings
