### ISSUE TITLE
Issue in buildUp when nRequired < nExisting and new = FALSE

### ISSUE THREAD

**Issue by janaobsteter** [HighlanderLab/SIMplyBee#486]
See test in L2

**Comment by janaobsteter** [comment]
Let's say we have a colony with 100 workers. Then the user calls this line:

`buildUp(colony, nWorkers = 70, exact = TRUE, new = FALSE)`

What should we do in such a case? Do nothing or remove 30 workers (i.e. return a colony with 70 "old" workers)?

**Comment by janaobsteter** [comment]
In the tests we have that we return a colony with 70 workers, hence I'll fix the code to work with that

**Comment by janaobsteter** [comment]
In #488

**Comment by gregorgorjanc** [comment]
@janaobsteter tricky edge case. Ideally we would not be hitting this edge case most times. I am open to either implementation, but please do make a note in the docs on what the implementation does for this edge case.

**Comment by janaobsteter** [comment]
Done and merged
