### ISSUE TITLE
Instructional Youtube Videos for SIMplyBee Workshop

### ISSUE THREAD

**Issue by LStrachan** [HighlanderLab/SIMplyBee#508]
Setting up a place to discuss ideas for any Youtube videos ideas we have for future workshops. 

TODO: 
- Go through vignettes and decide on main points we want to talk about 
- How much in detail do we want to do? 
- How many videos? One per topic/vignette or longer more descriptive ones?

**Comment by gregorgorjanc** [comment]
Some tips from the MOOC

* aim for videos shorter than 15 min, so we might need more videos per vignette

* one or at most few clear topics per video - sometimes identifying what the topic actually is takes most time!

* avoid too much detail per video, however these videos will effectively be mostly screencasts so we should revise vignettes and think where we have too much information or unlikely too little information

* it takes time to record videos so best if we use vignettes as talking points - winging it or trying to will just mean we have to repeat over and over and over and there will be more editing

* we can book UoE media studio and record there where they have sound proof rooms, good microphones, and they are happy to show us how to edit!!!

* Who should do which vignette? Ideally we do it while Jana is visiting us! Could Jernej come over at some point or shall we three do most of these?

**Comment by gregorgorjanc** [comment]
We will be doing this later in 2023 or start of 2024

We should make a video screencast of vignettes:

1A - Intro to honeybee biology - genome & castes & csd

2B - Multiple colonies

3C - Events

4D - Crossing

5E - Genomics

6F - QuanGen

7G - Sampling (maybe)

Possibly grand finale would be going over two templates

a) yearly cycle

b) Slovenian breeding cycle

And maybe later build a MOOC - after the pre-EAAP workshop

**Comment by gregorgorjanc** [comment]
Vignettes are likely sufficient given the resources (time, funding, personell) we have.
