### ISSUE TITLE
Add GitHub actions

### ISSUE THREAD

**Issue by gregorgorjanc** [HighlanderLab/SIMplyBee#514]
Apparently we can set GitHub actions to:
0) Check the package
1) Submit to CRAN
2) Push/puslich website
etc.

How do we do this?

**Comment by janaobsteter** [comment]
We do have the check action added - however, it keeps failing so I gave up on it :sweat: But we can have another look and also how to use them for the website.

**Comment by gregorgorjanc** [comment]
@LStrachan can you share here what actions have been implemented

**Comment by LStrachan** [comment]
Currently in the .github/workflow file we have two workflows. One for the R-CMD-check and one for Pkgdown (both are yaml files). 
Whenever there is an update, both of these automatically run. You can see them running/their progress when clicking on Actions in the top bar, clicking on the job and clicking again on the running job. This will also show where any errors occur if they do to make changes to the yaml files

**Comment by gregorgorjanc** [comment]
I think this probably suffices for now. It would be good to also get automatic code formatting #309
