### ISSUE TITLE
Do we now have our own setMisc and getMisc that intefere with the AlphaSimR's?

### ISSUE THREAD

**Issue by janaobsteter** [HighlanderLab/SIMplyBee#584]
Not sure about this, just writing it down so that we check. The package is now on CRAN, so the current main will reflect that. We can correct everything in the next push

**Comment by gregorgorjanc** [comment]
Are you getting any errors @janaobsteter ?

**Comment by janaobsteter** [comment]
It doesn't throw an error but it could be that one masks the other. Tbh, I forgot to check before submitting to CRAN

**Comment by gregorgorjanc** [comment]
I would imagine that we would get some tests failing!? I think that NAMESPACEs should help us here, but maybe we will have to make it a generic method with different versions for Pop vs Colony classes?

**Comment by janaobsteter** [comment]
Related to #285  and #144 . Implemented in #625
