### ISSUE TITLE
Create a function to sample a location for the swarm

### ISSUE THREAD

**Issue by janaobsteter** [HighlanderLab/SIMplyBee#8]

**Comment by gregorgorjanc** [comment]
This is actually quite simple - we just take the current location and add a sample from N(0, s^2) to each coordinate to get a new location. This should suffice for most needs. If anyone wants anything more fancy, then they can use `setLocation()` to a swarm.

**Comment by gregorgorjanc** [comment]
Done in https://github.com/gregorgorjanc/SIMplyBee/commit/4ac21076cf2197b3f36766758f9c29507bae8444
