### ISSUE TITLE
Create a function to sample colonies or DCA within a radius to use their drones

### ISSUE THREAD

**Issue by janaobsteter** [HighlanderLab/SIMplyBee#9]

**Comment by janaobsteter** [comment]
I think the question from the PR pertains here. So, what argument do we use for sampling the new location?
Pasting you thoughts from the PR:

```
Hmm, at the moment we operate on (x,y) coordinates, and to sample a new (x,y) we need (dx,dy) where dxN(0,sigma_{dx}^2) and dyN(0,sigma_{dy}^2) so we need sigmas (SD) as input. This means that I did not need to implement the radius stuff at all;)

Having said this, someone might have idea about the radius but not the sigmas, which is what you are hinting at, correct? Maybe we provide a function to convert radius to sigmas? I guess also if we have a radius, then the two sigmas are equal, right? Is that really what you are asking? If so, can you copy this is a new spatial issue and we take it from there?
```

**Comment by gregorgorjanc** [comment]
I have found a way to sample a random point within a circle and implemented that in https://github.com/HighlanderLab/SIMplyBee/pull/502. This is better than what I implemented before. I show some details below. But, we might not need this function for mating stuff. Still, the function is used in swarming, and we can now use it for anything else, say for sampling a location of a DCA (though I am aware we can not save that location information in the DCA pop object)

This video explains the different methods for such sampling nicely. I have implemented the simplest - rejection sample - so I was also able to use the same function for uniform or spherical Gaussian sampling.

nubDotDev (2021) The BEST Way to Find a Random Point in a Circle https://youtu.be/4y_nmpv-9lI

```
x <- rcircle(n = 500)
lim <- range(x)
plot(x, xlim = lim, ylim = lim, main = "Uniform")

x <- rcircle(n = 500, uniform = FALSE)
lim <- range(x)
plot(x, xlim = lim, ylim = lim, main = "Gaussian")
```

![Rplot](https://user-images.githubusercontent.com/725834/216730061-860e89ab-ab57-4843-8853-6b05c3666d03.png)
![Rplot01](https://user-images.githubusercontent.com/725834/216730062-0d7a5383-d791-424b-b977-d11227d83be2.png)

**Comment by janaobsteter** [comment]
A question - do we want to sample within a circle with Gaussian probability or with equal probability - the latter assumes that there is a DCA and all the drones have the same probability?
@JerBub @gregorgorjanc

**Comment by gregorgorjanc** [comment]
This is the biological part that I don't know.

I think that Gaussian makes more sense - that a queen flies with higher probability to a closer DCA - or that drones fly to a closer DCA etc.

Jernej what does the bee science say?

**Comment by JerBub** [comment]
it is a two level question and answer:
- to create a dca it as Gregor saied (drones fly to cloaser dca)
- but when sampling drones for mating from dca, all drones should have same chances to mate. Execept if we simulete some fitne taits in drones.

**Comment by gregorgorjanc** [comment]
Done in devel:

https://github.com/HighlanderLab/SIMplyBee/commit/c9576aac81565b876b081a27716d9521cb654e5e
https://github.com/HighlanderLab/SIMplyBee/commit/ef119ab6ebd876fba7501d4da498a03a64668b29
https://github.com/HighlanderLab/SIMplyBee/commit/55b6b8c9c52a23126b1e0c8f640ecb2195af072f
https://github.com/HighlanderLab/SIMplyBee/commit/0d655da974f0f4d145988ec1d822fae6abec437c
https://github.com/HighlanderLab/SIMplyBee/commit/c9576aac81565b876b081a27716d9521cb654e5e
